### ISSUE TITLE
Error: Cannot find module 'node-dht-sensor'

### ISSUE THREAD

**Issue by renno-bih** [openhomeautomation/rpi-web-control#1]
I'm trying to run sensors_test.js but I always get this error:

```
module.js:338
    throw err;
          ^
Error: Cannot find module 'node-dht-sensor'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/pi/rpi-web-control/sensors_test/sensors_test.js:1:79)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
```

Sure, I downloaded node-dht-sensor from https://github.com/momenso/node-dht-sensor , builded from source using these commands:

```
$ node-gyp configure
$ node-gyp build
```

 ... but no matter what I do, I cannot solve this problem.

Any suggestions?

**Comment by marcoschwartz** [comment]
Hello,

I know there has been some changes in the node-dht-sensor library. I managed to installed it via npm just as usual, but I had to get the latest version of Node.js. You can do so by typing:

wget http://node-arm.herokuapp.com/node_latest_armhf.deb 
sudo dpkg -i node_latest_armhf.deb

Then just make a node -v to make sure it is updated :) Let me know how it goes!

**Comment by renno-bih** [comment]
I fixed it by downloading node-dht-sensor manually and by using full path like this:

```
var sensorLib = require('/home/pi/node-dht-sensor/build/Release/node-dht-sensor');
```

**Comment by kalmia11** [comment]
I also had problems installing node-dht-sensor. I found that several directories in root were not owned by root. I used chown root:root <directoryname> to fix this problem.
